# _config.yml
title: "Steve Kariuki"
name: "Steve Kariuki"
description: "Cybersecurity & Software Engineering Portfolio"
url: "https://yourdomain.github.io" # replace with your GitHub Pages URL
baseurl: "" # leave empty if deploying to root

# Author settings
author:
  name     : "Steve Kariuki"
  avatar   : "/assets/images/your-photo.jpg" # replace with your actual photo path
  bio      : "Cybersecurity professional | Secure DevOps | Cloud Security Enthusiast"
  location : "Kenya"
  email    : "stevekariuki5@gmail.com"
  github   : "Steve664"
  linkedin : "steve-kariuki"

# Theme settings
remote_theme: "mmistakes/minimal-mistakes"
plugins:
  - jekyll-include-cache
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Social
social:
  type:  Person
  name:  Steve Kariuki
  links:
    - "https://www.linkedin.com/in/steve-kariuki/"
    - "https://github.com/Steve664"
    - "mailto:stevekariuki5@gmail.com"

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/
paginate: 5
paginate_path: /page:num/

# Navigation
collections:
  portfolio:
    output: true
    permalink: /:collection/:name/

# Navigation links
nav:
  - title: "Home"
    url: /
  - title: "Resume"
    url: /#resume
  - title: "Projects"
    url: /#projects
  - title: "Lab Challenges"
    url: /#labs
  - title: "Contact"
    url: /#contact

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: single
      author_profile: true
  - scope:
      path: ""
      type: "pages"
    values:
      layout: single
      author_profile: true

# Optional SEO
seo:
  name: "Steve Kariuki"
  type: "Person"
  description: "Cybersecurity portfolio of Steve Kariuki"
  url: "https://yourdomain.github.io" # update with your domain
